import Head from 'next/head';
import Link from 'next/link';
import DeleteButton from '../components/DeleteButton';
import { Card, CardContent, Typography, Button, Box } from '@mui/material';
import { getData } from '../lib/fetchData';

const HomePage = async () => {
  const data = await getData();

  return (
    <>
      <Head>
        <title>Blog List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col items-center justify-center p-4 bg-gray-100">
        <div className="w-full max-w-xl">
          <Box textAlign="right" mb={2}>
            <Link href="/insertBlog">
              <Button variant="contained" className="bg-blue-600">
                Create New Blog
              </Button>
            </Link>
          </Box>
          {data?.map((dt) => (
            <Card key={dt.id} variant="outlined" className="mb-2 bg-gray-50 hover:bg-gray-200">
              <CardContent className="flex items-center justify-between">
                <Link href={`/detailBlog/${dt.id}`}>
                  <Typography variant="h7" className="flex-1">
                    {dt.title}
                  </Typography>
                </Link>
                <DeleteButton id={dt.id} />
              </CardContent>
            </Card>
          ))}
        </div>
      </main>
    </>
  );
};

export default HomePage;